### PR TITLE
Full Stack Budget App

### PR DESCRIPTION
**Pull request by Atril33**
## **Budget App**
_**In this Project, I have done these suggested requirements**_

Dear Reviewer, I've successfully completed the project, and here's a concise summary of the tasks I've accomplished:

**Summary:**

- Set up the project and installed Ruby on Rails.
- Created migrations for the required database tables.
- Established models for all tables.
- Developed controllers for all models.
- Crafted views for all tables.
- Addressed and fixed the N+1 query problem.
- Implemented user authentication using Devise.
- Managed user authorization using CanCanCan.
- Styled the project using CSS.
- Added unit and integration tests for all views, ensuring that all tests pass.

 - [Live Demo Link](http://145.14.158.81)
 - [Presentation Video](https://drive.google.com/file/d/1xb0cRTXeEnsZgeAm3SmDRLUVRXkPnIQX/view)

### CODE REVIEW

**Review by muneebulrehman — CHANGES_REQUESTED** [review]
Hi @Atril33 , 

Good job so far! I see you put a lot of effort into this project. However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- No linter errors
- Descriptive PR
- Good UI
- App working as expected.
- All tests passing.

## Required Changes ♻️
_Check the comments under the review._

As per the project requirements, the max length of the video should be 5 minutes, however, in your case, it is touching 7 minutes. Kindly re-record the video presentation keeping in mind this case and following the below guidelines.
image


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Atril33** [comment]
> Hi @Atril33 ,
> 
> Good job so far! I see you put a lot of effort into this project. However, there are some issues that you still need to work on to go to the next project but you are almost there!
> 
> ## Highlights
> * No linter errors
> * Descriptive PR
> * Good UI
> * App working as expected.
> * All tests passing.
> 
> ## Required Changes ♻️
> _Check the comments under the review._
> 
> As per the project requirements, the max length of the video should be 5 minutes, however, in your case, it is touching 7 minutes. Kindly re-record the video presentation keeping in mind this case and following the below guidelines. image
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Atril33** [comment]
> Hi @Atril33 ,
> 
> Good job so far! I see you put a lot of effort into this project. However, there are some issues that you still need to work on to go to the next project but you are almost there!
> 
> ## Highlights
> * No linter errors
> * Descriptive PR
> * Good UI
> * App working as expected.
> * All tests passing.
> 
> ## Required Changes ♻️
> _Check the comments under the review._
> 
> As per the project requirements, the max length of the video should be 5 minutes, however, in your case, it is touching 7 minutes. Kindly re-record the video presentation keeping in mind this case and following the below guidelines. image
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Atril33** [comment]
Hello @muneebulrehman, I hope you are doing well, I don't believe this is a valid reason for rejection. In my eight months in this program, I haven't seen any reviewers reject a project for this reason

**Comment by muneebulrehman** [comment]
> Hello @muneebulrehman, I hope you are doing well, I don't believe this is a valid reason for rejection. In my eight months in this program, I haven't seen any reviewers reject a project for this reason

Hey @Atril33, I understand your concern. But I am responsible for my own conduct and not for other code-reviewers. I also attached a screenshot in the PR summary of the guidelines that I have to follow. And I believe, in your project requirements, it is also mentioned there. The reason for this requirement is that you will not have enough time in a real interview to present your project. So, you need to be quick with this sort of communication and presentation.

**Comment by Atril33** [comment]
Dear Reviewer, It is very difficult for me to record a new video because there is electricity issue so please don't reject my project for this reason

**Review by uwadonat — APPROVED** [review]
## Hi @Atril33, 

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 


### Good luck! 🎉 


### Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @uwadonat in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Pull request merged**
